name: BayesianRegret_FixedAmplitude_CostAware
program: scripts/fixed_amplitude_cost_aware.py
method: grid
parameters:
  dim:
    values: [4,8,16,32,64]
  kernel:
    values: ["Matern32", "Matern52", "RBF"]
  lengthscale:
    values: [0.01, 0.1,1.0]
  amplitude:
    values: [1.0]
  seed:
    values: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
  input_normalization:
    value: False
  draw_initial_method:
    values: ['sobol']
  policy:
    values:
      - ExpectedImprovement
      - ExpectedImprovementWithCost_Uniform
      - ExpectedImprovementWithCost_Cooling
      # - BudgetedMultiStepExpectedImprovement
      - Gittins_Lambda_01
      - Gittins_Lambda_001
      - Gittins_Lambda_0001
      - Gittins_Step_Divide2
      - Gittins_Step_Divide5
      - Gittins_Step_Divide10
      - Gittins_Step_EIpu
  costs:
    values: ['linear', 'periodic']