name: BayesianRegret_VariableAmplitude
program: scripts/variable_amplitude.py
method: grid
parameters:
  kernel:
    values: ["matern32", "matern52"]
  dim:
    values: [1]
  lengthscale:
    values: [0.01]
  amplitude:
    values: [1.0]
  num_rff_features:
    value: 1280
  seed:
    values: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
  input_normalization:
    value: False
  policy:
    values:
      - ExpectedImprovement
      - ExpectedImprovementWithCost_Uniform
      - ExpectedImprovementWithCost_Cooling
      # - BudgetedMultiStepExpectedImprovement
      - Gittins_Lambda_01
      - Gittins_Lambda_001
      - Gittins_Lambda_0001
      - Gittins_Step_Divide2
      - Gittins_Step_Divide5
      - Gittins_Step_Divide10
      - Gittins_Step_EIpu
  problem:
    values: ['hard_for_eipc', 'hard_for_ei']