name: BayesianRegret_FixedAmplitude
program: scripts/fixed_amplitude.py
method: grid
parameters:
  kernel:
    values: ["matern52"]
  dim:
    values: [1,2,4]
  lengthscale:
    values: [0.1,1.0]
  amplitude:
    values: [1.0]
  num_rff_features:
    value: 1280
  seed:
    values: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  input_normalization:
    value: false
  policy:
    values:
      - ExpectedImprovement
      # - ThompsonSampling
      # - PredictiveEntropySearch
      # - MultiStepExpectedImprovement
      - Gittins_Lambda_01
      - Gittins_Lambda_001
      - Gittins_Lambda_0001
      - Gittins_Step_Divide2
      - Gittins_Step_Divide5
      - Gittins_Step_Divide10
      - Gittins_Step_EIpu