name: BayesianRegret_VariableAmplitude
program: scripts/variable_amplitude.py
method: grid
parameters:
  kernel:
    values: ["matern32", "matern52"]
  dim:
    values: [1,2,4,8,16]
  lengthscale:
    values: [0.01]
  num_rff_features:
    value: 1280
  seed:
    values: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
  input_normalization:
    value: false
  max_num_iterations:
    value: 100
  draw_initial_method:
    values: ['deterministic_boundary']
  total_cost_budget:
    value: 11.0
  policy:
    values:
      - ExpectedImprovementPerCost
      - ExpectedImprovement_UniformCost
      - ExpectedImprovementPerCost_WithCooling
      - BudgetedMultiStepExpectedImprovement
      - Gittins_Lambda_10
      - Gittins_Lambda_01
      - Gittins_Lambda_001
      - Gittins_Step
      - Gittins_Step_EIPC
  costs:
    values: ['hard_for_eipc','hard_for_ei','hard_for_both']
  cost_function_epsilon:
    value: 0.1
  cost_function_delta:
    value: 10
  cost_function_width:
    value: 0.001