name: Empirical
program: scripts/empirical.py
method: grid
parameters:
  problem:
    values: ["LunarLander", "PestControl", "RobotPushing14D"]
  seed:
    values: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
  input_normalization:
    value: True
  draw_initial_method:
    values: ['sobol']
  policy:
    values:
      - RandomSearch
      - ExpectedImprovement
      - ThompsonSampling
      # - PredictiveEntropySearch
      - Gittins_Lambda_01
      - Gittins_Lambda_001
      - Gittins_Lambda_0001
      - Gittins_Step_Divide2
      - Gittins_Step_Divide5
      - Gittins_Step_Divide10
      - Gittins_Step_EIpu
      - KnowledgeGradient
      - MultiStepLookaheadEI

