name: Empirical_CostAware
program: scripts/empirical_cost_aware.py
method: grid
parameters:
  problem:
    values: ['LDA']
  seed:
    values: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  input_normalization:
    value: True
  draw_initial_method:
    values: ['sobol']
  policy:
    values:
      - ExpectedImprovement
      - ExpectedImprovementWithCost_Uniform
      - ExpectedImprovementWithCost_Cooling
      # - BudgetedMultiStepExpectedImprovement
      - Gittins_Lambda_01
      - Gittins_Lambda_001
      - Gittins_Lambda_0001
      - Gittins_Step
      - Gittins_Step_EIpu

