name: LmbdaImpact
program: scripts/impact_of_lmbda.py
method: grid
parameters:
  dim:
    values: [8]
  kernel:
    values: ["Matern52"]
  lengthscale:
    values: [1.0,0.1]
  amplitude:
    values: [1.0]
  seed:
    values: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
  input_normalization:
    value: false
  draw_initial_method:
    values: ['sobol']
  policy:
    values:
      # - RandomSearch
      # - ExpectedImprovement
      # - ThompsonSampling
      # - UpperConfidenceBound
      # - PredictiveEntropySearch
      # - KnowledgeGradient
      - Gittins_Lambda_1
      - Gittins_Lambda_01
      - Gittins_Lambda_001
      - Gittins_Lambda_0001
      - Gittins_Lambda_00001
      - Gittins_Step_Divide2
      # - Gittins_Step_Divide5
      # - Gittins_Step_Divide10
      # - Gittins_Step_EIpu
