name: RegretGapOpt
program: scripts/compute_regret_gap.py
method: bayes
metric:
  name: median_regret_gap
  goal: maximize
parameters:
  dim:
    values: [10, 12, 14, 16, 18, 20, 22, 24]
  lengthscale:
    distribution: log_uniform_values
    min: 0.01
    max: 1.0
  Gittins_lmbda:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.01
  kernel:
    value: 'Matern52'
  amplitude:
    value: 1.0
  input_normalization:
    value: false
  draw_initial_method:
    value: 'sobol'
  num_iterations:
    value: 200
  