name: Synthetic
program: scripts/synthetic.py
method: grid
parameters:
  problem:
    values: ["Ackley_5D", "DropWave_2D", "Shekel5_4D", "Levy_5D", "Rosenbrock_5D"]
  seed:
    values: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
  normalization:
    values: [True,False]
  num_iterations:
    value: 50
  draw_initial_method:
    values: ['sobol']
  policy:
    values:
      - ExpectedImprovement
      - ThompsonSampling
      - PredictiveEntropySearch
      - MultiStepExpectedImprovement
      - Gittins_Lambda1
      - Gittins_Lambda01
      - Gittins_Lambda001
      - Gittins_Step_Divide2
      - Gittins_Step_EIpu

