name: Synthetic_CostAware
program: scripts/synthetic_cost_aware.py
method: grid
parameters:
  problem:
    values: ["Ackley", "Levy", "Rosenbrock"]
  dim:
    values: [4, 8, 16]
  seed:
    values: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
  output_standardize:
    values: [True]
  draw_initial_method:
    values: ['sobol']
  policy:
    values:
      - RandomSearch
      - ExpectedImprovementWithoutCost
      - ExpectedImprovementPerUnitCost
      - ExpectedImprovementWithCostCooling
      - MultiFidelityMaxValueEntropy
      - Gittins_Lambda_01
      - Gittins_Lambda_001
      - Gittins_Lambda_0001
      - GittinsDecay_InitLambda_0001
      - BudgetedMultiStepLookaheadEI
  cost_function_type:
    values: ['mean']
  budget_to_dimension_ratio:
    value: 25
  cost_min:
    value: 0.05
  cost_function_scale_factor:
    value: 20
  max_to_min_ratio:
    value: 21

