name: Synthetic_CostAware
program: scripts/synthetic_cost_aware.py
method: grid
parameters:
  problem:
    values: ["Ackley_5D", "DropWave_2D", "Shekel5_4D", "Levy_5D", "Rosenbrock_5D"]
  seed:
    values: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
  input_normalization:
    values: [True]
  total_cost_budget:
    value: 60
  draw_initial_method:
    values: ['sobol']
  policy:
    values:
      - ExpectedImprovement
      - ExpectedImprovementWithCost_Uniform
      - ExpectedImprovementWithCost_Cooling
      - BudgetedMultiStepLookaheadEI
      - Gittins_Lambda_01
      - Gittins_Lambda_001
      - Gittins_Lambda_0001
      - Gittins_Step_Divide2
      - Gittins_Step_Divide5
      - Gittins_Step_Divide10
      - Gittins_Step_EIpu

