name: Synthetic
program: scripts/synthetic.py
method: grid
parameters:
  problem:
    values: ["Ackley", "Rosenbrock", "Levy"]
  dim:
    values: [4, 8, 16]
  seed:
    values: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
  output_normalization:
    values: [True]
  draw_initial_method:
    values: ['sobol']
  policy:
    values:
      - RandomSearch
      - ThompsonSampling
      - ExpectedImprovement
      - UpperConfidenceBound
      # - PredictiveEntropySearch
      - KnowledgeGradient
      - MultiStepLookaheadEI
      - Gittins_Lambda_01
      - Gittins_Lambda_001
      - Gittins_Lambda_0001
      - Gittins_Step_Divide2
      - Gittins_Step_Divide5
      - Gittins_Step_Divide10
      - Gittins_Step_EIpu

