name: synthetic_test
program: scripts/synthetic_test.py
method: grid
parameters:
  problem:
    value: 'Levy'
  dim:
    value: 5
  global_optimum:
    value: 0
  num_iterations:
    value: 50
  seed:
    values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
  draw_initial_method:
    values: ['sobol']
  policy:
    values: ['EI','GIhalving', 'GIdecay2', 'GIdecay8', 'GIdecay32', 'GIdecay128']

