name: test
program: scripts/bayesopt.py
method: grid
parameters:
  kernel:
    values: ["matern12","matern32","matern52"]
  dim:
    values: [2,4,8,16,32]
  length_scale:
    values: [0.1,1.0,10.0]
  amplitude:
    values: [1.0]
  seed:
    values: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
  num_iterations:
    value: 100
  acquisition_function:
    values: ['EIpc','Gittins']
