name: variable_amplitude
program: scripts/variable_amplitude.py
method: grid
parameters:
  kernel:
    values: ["matern12"]
  dim:
    values: [1]
  lengthscale:
    values: [0.01]
  amplitude:
    values: [1.0]
  num_rff_features:
    value: 1280
  seed:
    values: [42]
  budget:
    value: 3.0
  policy:
    values: ['EI','EIpu','EIcool', 'GIfree', 'GIlmbda']
