name: variable_amplitude
program: scripts/variable_amplitude.py
method: grid
parameters:
  kernel:
    values: ["matern12","matern32","matern52"]
  dim:
    values: [1]
  length_scale:
    values: [0.01,0.1,1.0]
  amplitude:
    values: [1.0]
  seed:
    values: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
  budget:
    value: 3.0
  acquisition_function:
    values: ['EI','EIpu','EIcool', 'GIlmbda', 'GIfree']
